### ISSUE TITLE
Feature Request: pillar.round = FALSE

### ISSUE THREAD

**Issue by charliejhadley** [r-lib/pillar#97]
It would be beneficial to have an option `pillar.round` to control the rounding of numbers that straddle 0 - 1.

In the following example the `straddle` column has been subject to rounding as `pillar.sigfig = 3` by default:

```r
library("tidyverse")
#> ── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1     ✔ purrr   0.2.4
#> ✔ tibble  1.4.2     ✔ dplyr   0.7.4
#> ✔ tidyr   0.8.0     ✔ stringr 1.2.0
#> ✔ readr   1.1.1     ✔ forcats 0.2.0
#> ── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ dplyr::filter() masks stats::filter()
#> ✖ dplyr::lag()    masks stats::lag()
my_numbers <-  c(233, 486, 565, 785)
straddle_data <- tibble(
  big = 1000 * my_numbers + 23,
  stradle = my_numbers / 1000 + 100,
  small = my_numbers / 100000
)
straddle_data
#> # A tibble: 4 x 3
#>      big straddle   small
#>    <dbl>   <dbl>   <dbl>
#> 1 233023     100 0.00233
#> 2 486023     100 0.00486
#> 3 565023     101 0.00565
#> 4 785023     101 0.00785
```

In order to display the fractional component of `straddle`  straddle we need to massively pad the `small` column with `pillar.sigfig = 7`

```r
options(pillar.sigfig = 7)
straddle_data
#> # A tibble: 4 x 3
#>      big straddle       small
#>    <dbl>    <dbl>       <dbl>
#> 1 233023  100.233 0.002330000
#> 2 486023  100.486 0.004860000
#> 3 565023  100.565 0.005650000
#> 4 785023  100.785 0.007850000
```

It would be useful for the following to work (note the use of \*233\* to indicate the portion of the output that is highlighted thanks to `pillar.subtle = TRUE`) 

```r
options(pillar.round = FALSE)
straddle_data
#> # A tibble: 4 x 3
#>      big straddle       small
#>    <dbl>    <dbl>   <dbl>
#> 1 *233*023      *100*.233 0.00*233*
#> 2 *486*023      *100*.486 0.00*486*
#> 3 *565*023      *100*.565 0.00*565*
#> 4 *785*023      *100*.785 0.00*785*
```
I appreciate the comment from @hadley here https://github.com/r-lib/pillar/issues/40#issuecomment-360152576 about using a trailing `.` but I think this is a different problem to what was discussed in that issue.

**Comment by krlmlr** [comment]
Thanks. I agree we need to think more about how to represent numbers of the same magnitude but with subtle differences.

**Comment by kabuhr** [comment]
+1 on this feature.  I understand the motivation for showing only significant digits, and I'd even be prepared to agree that this makes sense when the emphasis is on **analysis** of **measured**, **physical** data.  However, when we're working with certain types of data (currency values,  ID numbers that for one unfortunate reason or another have been stored as doubles instead of ints) or when we're working on a pipeline of functions to perform some data manipulation (rather than just an "analysis") and trying to verify that the logic is working correctly at each step, this default of aggressive, three-sigdig rounding is both surprising and confusing.

This is a case where vanilla R basically got it right.  The logic in ``print.default()`` makes sense, rarely produces surprising results, and only occasionally produces ugly output.  From the help page:

> The same number of decimal places is used throughout a vector. This means that [the global option] ‘digits’ specifies the minimum number of significant digits to be used, and that at least one entry will be encoded with that minimum number.  However, if all the encoded elements then have trailing zeroes, the number of decimal places is reduced until at least one element has a non-zero final digit. Decimal points are only included if at least one decimal place is selected.

I would suggest that the proposed ``pillar.round=FALSE`` should switch to the vanilla R method, using the global ``options("digits")`` option (with its relatively high default of 7) together with the same logic quoted above.  Combined with ``pillar.subtle=TRUE`` to de-emphasize trailing digits beyond ``pillar.sigfig``, this would be just about perfect, combining the "no surprises" approach from ``print.default()`` with a gentle "hey that 5th significant digit probably shouldn't be included in your final results" reminder.

In fact, if I had may way, this would be the **default** behavior, though I understand why some people would prefer the current default with its pre-rounded answers.

**Comment by StephieLaPugh** [comment]
Curious as to the status of this. I've been struggling all morning trying to make a summary tibble display a consistent number of decimal places (i.e., simply match the data as read in from Excel with two decimals). I am working with a group of consultants who are ride-or-die Excel folks, and if I can't prove to them that R (+tidyverse) will make their life _better_ rather than more confusing and complicated, I will struggle to get traction. This is an example of something that is effortless in Excel ("I want to see these numbers with three decimals" click, click done), but that has now taken me an hour to learn that other than changing `pillar.sigfig=x` -- which is not really what I want -- I can't even do it. 

My only option as I see it is to produce a gt (or similar) table -- a whole other step and chunk of code -- just to control something that is a click or two in Excel. Now when a colleague asks me, "why is it rounding this column but not those?" "can you make it match the spreadsheet?" and I have to say, "no, we don't get to do that, because... something." I will get a snort and a pat on the head and they will go back to their rectangles. Which makes me sad. Rounding, please!

**Comment by yimingli** [comment]
Spent an hour trying to understand where all the decimal points are gone, before the trailing `.` caught my eyes, and googled what it means. Maybe we can at least show some decimal points in RStudio's table view, where column width are adjustable by dragging left and right?

**Comment by DasHammett** [comment]
Late to the party, but this is the only reason I am stripping all formatting of tibbles by overwriting ```print.tbl_df```
By doing so, I am also removing all the other nice features of tibbles that I love, but the fact that I *cannot* control decimal points on my data drives me nuts.

There are also a lot of inconsistencies if you increase ```pillar.sigfig``` to the point where in the same column, some rows will not show trailing zeros, but some will. Also notice that I need a ridiculously high ```pillar.sigfig``` number to show just 2 decimal points in the ```silly_test``` column

```
options(pillar.sigfig = 7)
iris %>% mutate(silly_test = Sepal.Length * 1000 * pi) %>% as_tibble()

# A tibble: 150 x 6
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species silly_test
          <dbl>       <dbl>        <dbl>       <dbl> <fct>        <dbl>
 1     5.100000         3.5          1.4         0.2 setosa    16022.12
 2     4.9              3            1.4         0.2 setosa    15393.80
 3     4.7              3.2          1.3         0.2 setosa    14765.49
 4     4.600000         3.1          1.5         0.2 setosa    14451.33
 5     5                3.6          1.4         0.2 setosa    15707.96
 6     5.4              3.9          1.7         0.4 setosa    16964.60
 7     4.600000         3.4          1.4         0.3 setosa    14451.33
 8     5                3.4          1.5         0.2 setosa    15707.96
 9     4.4              2.9          1.4         0.2 setosa    13823.01
10     4.9              3.1          1.5         0.1 setosa    15393.80
# … with 140 more rows
```
IMHO there are far too many scenarios where ```pillar.sigfig``` produces ill and prone to confusion results, that this should have never been implemented. I understand the logic behind it, but the implementation approach without a way out has been very offputting.

I *really* hope there will be a future option to opt out of sigfig altogether for those who find it extremely confusing and annoying to work with

**Comment by rsuhada** [comment]
It's 3 years later and decimal place display still trips me up.... Tidyverse is full of excellent design choices that help the user work correctly, yet you get by default:
 ```
print(tibble(x=10.0 + 0.05))
 # A tibble: 1 x 1
   x
  <dbl>
1  10.0
```
It makes it so hard to check calculations by glance...

**Comment by krlmlr** [comment]
@rsuhada: Please set the `"pillar.sigfig"` option to a larger value if desired. This issue is about adaptively increasing the accuracy if all numbers are very similar. See https://pillar.r-lib.org/dev/articles/digits.html for a comparison of base and pillar options.

**Comment by rsuhada** [comment]
I apologize, but I don't think setting `pillar.sigfig` to a different value every time I need to see my numbers is a good solution.

The thread is a general request to turn off pillar formatting completely in the session without loosing other tibble conveniences.
I think several, relevant, real world use cases have been identified where pillar formatting is to detriment.

I understand that this is your baby and maybe you have good research into accessibility and human interaction with numerical data, but I really don't think I'm alone in stumbling into this. If you want to keep it as default OK, but we need a way to turn it off completely in my opinion.

**Comment by DasHammett** [comment]
> @rsuhada: Please set the `"pillar.sigfig"` option to a larger value if desired. This issue is about adaptively increasing the accuracy if all numbers are very similar.
> 
> See https://pillar.r-lib.org/dev/articles/digits.html for a comparison of base and pillar options.

Hi,

You are not understanding the issue here. The problem is not that pillar is not adapting accuarcy, but the inability to control the decimal places. There are examples above which illustrate the issue and yet the "official" solution is to increase `pillar.sigfig` which produces undesirable side effects, while not solving the issue for larger numbers. Examples above.

We are fine you don't want to remove it, we just want a way to opt out without losing all the other features.

**Comment by krlmlr** [comment]
To turn off pillar formatting, use:

``` r
my_numbers <- c(233, 486, 565, 785)
df <- data.frame(
  big = 1000 * my_numbers + 23,
  straddle = my_numbers / 1000 + 100,
  small = my_numbers / 100000
)
tbl <- tibble::as_tibble(df)

tbl
#> # A tibble: 4 x 3
#>      big straddle   small
#>    <dbl>    <dbl>   <dbl>
#> 1 233023     100. 0.00233
#> 2 486023     100. 0.00486
#> 3 565023     101. 0.00565
#> 4 785023     101. 0.00785

print.tbl <- function(x, ...) {
  print.data.frame(x, ...)
  invisible(x)
}

# Necessary for now
print.tbl_df <- print.tbl

tbl
#>      big straddle   small
#> 1 233023  100.233 0.00233
#> 2 486023  100.486 0.00486
#> 3 565023  100.565 0.00565
#> 4 785023  100.785 0.00785
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Where should we document this?

The next comment shows why I think this won't solve the underlying issue.

**Comment by krlmlr** [comment]
As far as I can tell, the thread hinges on the following example:

``` r
my_numbers <- c(233, 486, 565, 785)
df <- data.frame(
  big = 1000 * my_numbers + 23,
  straddle = my_numbers / 1000 + 100,
  small = my_numbers / 100000
)
tbl <- tibble::as_tibble(df)

options(pillar.sigfig = 7)
df
#>      big straddle   small
#> 1 233023  100.233 0.00233
#> 2 486023  100.486 0.00486
#> 3 565023  100.565 0.00565
#> 4 785023  100.785 0.00785
tbl
#> # A tibble: 4 x 3
#>      big straddle   small
#>    <dbl>    <dbl>   <dbl>
#> 1 233023  100.233 0.00233
#> 2 486023  100.486 0.00486
#> 3 565023  100.565 0.00565
#> 4 785023  100.785 0.00785

options(pillar.sigfig = NULL)
options(digits = 3)
df
#>      big straddle   small
#> 1 233023      100 0.00233
#> 2 486023      100 0.00486
#> 3 565023      101 0.00565
#> 4 785023      101 0.00785
tbl
#> # A tibble: 4 x 3
#>      big straddle   small
#>    <dbl>    <dbl>   <dbl>
#> 1 233023     100. 0.00233
#> 2 486023     100. 0.00486
#> 3 565023     101. 0.00565
#> 4 785023     101. 0.00785
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The `straddle` column doesn't show the differences between the numbers in the `straddle` column with pillar's default setting, neither does it when we set `options(digits = 3)`. It's easy to set `options(pillar.sigfig = <large>)` in a project's or user-defined `.Rprofile` to achieve greater accuracy at the expense of sometimes unnecessary detail. Increasing this option gives very similar results to data frame output, the only difference is the trailing dot that indicates that there are more decimal places. Happy to review an example where the default base output is genuinely better than pillar output with `options(pillar.sigfig = 7)` .

Now, for any given value of the `"pillar.sigfig"` option, we can increase the magnitude of the `straddle` column so that the decimal places are not shown -- neither with the pillar output nor with the default data frame output:

``` r
my_numbers <- c(233, 486, 565, 785)
df <- data.frame(
  straddle = my_numbers / 1000 + 1000000
)
tbl <- tibble::as_tibble(df)

options(pillar.sigfig = 7)
df
#>   straddle
#> 1  1000000
#> 2  1000000
#> 3  1000001
#> 4  1000001
tbl
#> # A tibble: 4 x 1
#>   straddle
#>      <dbl>
#> 1 1000000.
#> 2 1000000.
#> 3 1000001.
#> 4 1000001.
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

One solution here would be to adaptively increase the number of significant figures in cases where all numbers have very similar magnitude but subtle differences. I'm not sure if this should be the default behavior, an option, or perhaps part of `num()`: https://pillar.r-lib.org/dev/reference/num.html .

**Comment by DasHammett** [comment]
> The `straddle` column doesn't show the differences between the numbers in the `straddle` column with pillar's default setting, neither does it when we set `options(digits = 3)`. It's easy to set `options(pillar.sigfig = <large>)` in a project's or user-defined `.Rprofile` to achieve greater accuracy at the expense of sometimes unnecessary detail. Increasing this option gives very similar results to data frame output, the only difference is the trailing dot that indicates that there are more decimal places.` 

Absolutely not the same. The difference is that in a dataframe we get the same number of decimal places REGARDLESS of the magnitude of the number  while in `pillar` it is necessary to adapt it for every number, ie, `options(digits = 3) != options(pillar.sigfig = 3)`.

> Happy to review an example where the default base output is genuinely better than pillar output with `options(pillar.sigfig = 7`

You already have examples in this thread that show df output to be better at precision and readability. I understand this is subjective and my understanding of "genuinely better" is probably different than yours. For me a format that does not represent data accurately is not genuinely better.

```
print(tibble(x=10.0 + 0.05))
# A tibble: 1 x 1
  x
 <dbl>
1  10.0
```

From your own example I get different output:
```
my_numbers <- c(233, 486, 565, 785)
df <- data.frame(
  big = 1000 * my_numbers + 23,
  straddle = my_numbers / 1000 + 1000,
  small = my_numbers / 100000
)
tbl <- tibble::as_tibble(df)

options(pillar.sigfig = 7)
> tbl
# A tibble: 4 x 3
     big straddle       small
   <dbl>    <dbl>       <dbl>
1 233023  100.233 0.00233
2 486023  100.486 0.00486
3 565023  100.565 0.00565
4 785023  100.785 0.007850000
> df
     big straddle   small
1 233023  100.233 0.00233
2 486023  100.486 0.00486
3 565023  100.565 0.00565
4 785023  100.785 0.00785
```
This output is with tibble v 3.0.3. I am not sure why you are not getting the same output though.

I hope you agree that the solution to this problem cannot be to strip everything from the tibble as you suggest. It is the only solution now, but I do hope to have a more sensible option in the future where I can enjoy the rest of the tibble formatting without the problems of sigfig. 

It also surprises me how reticent you are to add an opt-out option to this behaviour that we have proven to be problematic time and time again. From the `num()` reference you posted it would seem to be a `digits` option that would do the trick, but it not compatible with `sigfig`. Perhaps a option to toggle between the two might be the best so users can choose from them.

**Comment by krlmlr** [comment]
Please give an example where `options(digits = 3) != options(pillar.sigfig = 3)` . AFAICT, all examples in this thread show that it's essentially the same. The default `options(digits = 7)` show more precision, but so does `options(pillar.sigfig = 7)` .

``` r
options(digits = 3)

data.frame(x = 10.05)
#>      x
#> 1 10.1
tibble::tibble(x = 10.05)
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1  10.0

options(digits = 7)
options(pillar.sigfig = 7)

data.frame(x = 10.05)
#>       x
#> 1 10.05
tibble::tibble(x = 10.05)
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1 10.05
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The `0.007850000` was a buglet that is fixed in current pillar.

See https://pillar.r-lib.org/articles/extending.html#restyle-body for an option to restyle the body of a tibble without changing the rest.

Please let me know if any of the options in `num()` work for you. If not, please open a separate issue.

**Comment by hadley** [comment]
@DasHammett this sort of language is not helpful:

> It also surprises me how reticent you are to add an opt-out option to this behaviour that we have proven to be problematic time and time again.

You have not proven anything to us. We have taken steps to improve the problem in the development version, but they don't seem to be helping you and you are failing to convey exactly what the problem is. I would suggest installing the development version of dplyr and working develop a couple of reprexes that crisply explain your issue.

**Comment by DasHammett** [comment]
@hadley Apologies if my message came out as not helpful, it is definitely not my intention here. I let my frustration speak on my behalf. I have been overwriting the tibble printing for 2+ years and did not notice the advancements you have made.

I took your suggestion and installed the developement version of dplyr and I must say it is almost perfect. But unfortunately I am still having some issues.

The example below uses geospatial data and calculates the great distance between an origin and the set of coordinates.
```
library(geosphere)
lat <- c(2.19530185019, 2.19530185019, 2.16478530044, 1.13056809668, 1.13149200000, 1.13066607245, 1.13042366000, 2.16163929764, 2.16017258534, 2.19530185019, 2.19530185019, 1.24   425900000, 2.19530185019, 2.10695278000, 2.19838307408, 2.16163929764, 2.16017258534, 1.87536835670, 1.88084059295, 2.19530185019)
lon <- c( 41.4168116699, 41.4168116699, 41.3745021149, 42.4112932739, 42.4121110000, 42.4114328014, 42.4111942700, 41.3814433019, 41.3780043185, 41.4168116699, 41.4168116699, 42.   5150562000, 41.4168116699, 41.5105799400, 41.4402062712, 41.3814433019, 41.3780043185, 42.2349025794, 41.9442408387, 41.4168116699)
origin <- c(1.1952050041416435,42.41829191947389)

df <- data.frame(lat = lat, lon = lon)
df$distance <- distHaversine(origin,df[,c("lat","lon")])

options(digits = 7)
options(pillar.sigfig = 7)

df
        lat      lon   distance
1  2.195302 41.41681 138891.335
2  2.195302 41.41681 138891.335
3  2.164785 41.37450 141262.131
4  1.130568 42.41129   5369.016
5  1.131492 42.41211   5281.238
6  1.130666 42.41143   5358.809
7  1.130424 42.41119   5382.372
8  2.161639 41.38144 140476.048
9  2.160173 41.37800 140722.898
10 2.195302 41.41681 138891.335
11 2.195302 41.41681 138891.335
12 1.244259 42.51506  11500.293
13 2.195302 41.41681 138891.335
14 2.106953 41.51058 126115.959
15 2.198383 41.44021 136955.312
16 2.161639 41.38144 140476.048
17 2.160173 41.37800 140722.898
18 1.875368 42.23490  59584.024
19 1.880841 41.94424  77353.483
20 2.195302 41.41681 138891.335

tibble::as_tibble(df)
# A tibble: 20 x 3
        lat      lon   distance
      <dbl>    <dbl>      <dbl>
 1 2.195302 41.41681 138891.3
 2 2.195302 41.41681 138891.3
 3 2.164785 41.37450 141262.1
 4 1.130568 42.41129   5369.016
 5 1.131492 42.41211   5281.238
 6 1.130666 42.41143   5358.809
 7 1.130424 42.41119   5382.372
 8 2.161639 41.38144 140476.0
 9 2.160173 41.37800 140722.9
10 2.195302 41.41681 138891.3
11 2.195302 41.41681 138891.3
12 1.244259 42.51506  11500.29
13 2.195302 41.41681 138891.3
14 2.106953 41.51058 126116.0
15 2.198383 41.44021 136955.3
16 2.161639 41.38144 140476.0
17 2.160173 41.37800 140722.9
18 1.875368 42.23490  59584.02
19 1.880841 41.94424  77353.48
20 2.195302 41.41681 138891.3
```
As you can see the tibble print is not the same as the df. It would seem as `pillar` is calculating the `pillar.sigfig` for each row and based on that displays the value, with varying degrees of precision. The dataframe seems to calculate what is the maximum decimal places for the entire `distance` column.

@krlmlr This is what I meant when I said `options(digits = 3) != options(pillar.sigfig = 3)`. I am sorry I was not able to express it better in my previous comment.

I hope this example make the issue clearer, let me know if more examples are required.

**Comment by hadley** [comment]
@DasHammett Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by DasHammett** [comment]
@hadley  Sure. For some reason `reprex()` throws an error on my linux machine, so I had to go to another machine.

``` r
library(geosphere)
#> Warning: package 'geosphere' was built under R version 4.0.3
lat <- c(2.19530185019, 
         2.19530185019, 
         2.16478530044, 
         1.13056809668, 
         1.13149200000, 
         1.13066607245, 
         1.13042366000, 
         2.16163929764, 
         2.16017258534, 
         2.19530185019, 
         2.19530185019, 
         1.24425900000, 
         2.19530185019, 
         2.10695278000, 
         2.19838307408, 
         2.16163929764, 
         2.16017258534, 
         1.87536835670, 
         1.88084059295, 
         2.19530185019
         )
lon <- c( 41.4168116699, 
          41.4168116699, 
          41.3745021149, 
          42.4112932739, 
          42.4121110000, 
          42.4114328014, 
          42.4111942700, 
          41.3814433019, 
          41.3780043185, 
          41.4168116699, 
          41.4168116699, 
          42.5150562000, 
          41.4168116699, 
          41.5105799400, 
          41.4402062712, 
          41.3814433019, 
          41.3780043185, 
          42.2349025794, 
          41.9442408387, 
          41.4168116699
          )
origin <- c(1.1952050041416435,42.41829191947389)

df <- data.frame(lat = lat, lon = lon)
df$distance <- distHaversine(origin,df[,c("lat","lon")])

options(digits = 7)
options(pillar.sigfig = 7)

df
#>         lat      lon   distance
#> 1  2.195302 41.41681 138891.335
#> 2  2.195302 41.41681 138891.335
#> 3  2.164785 41.37450 141262.131
#> 4  1.130568 42.41129   5369.016
#> 5  1.131492 42.41211   5281.238
#> 6  1.130666 42.41143   5358.809
#> 7  1.130424 42.41119   5382.372
#> 8  2.161639 41.38144 140476.048
#> 9  2.160173 41.37800 140722.898
#> 10 2.195302 41.41681 138891.335
#> 11 2.195302 41.41681 138891.335
#> 12 1.244259 42.51506  11500.293
#> 13 2.195302 41.41681 138891.335
#> 14 2.106953 41.51058 126115.959
#> 15 2.198383 41.44021 136955.312
#> 16 2.161639 41.38144 140476.048
#> 17 2.160173 41.37800 140722.898
#> 18 1.875368 42.23490  59584.024
#> 19 1.880841 41.94424  77353.483
#> 20 2.195302 41.41681 138891.335


tibble::as_tibble(df)
#> # A tibble: 20 x 3
#>         lat      lon   distance
#>       <dbl>    <dbl>      <dbl>
#>  1 2.195302 41.41681 138891.3  
#>  2 2.195302 41.41681 138891.3  
#>  3 2.164785 41.37450 141262.1  
#>  4 1.130568 42.41129   5369.016
#>  5 1.131492 42.41211   5281.238
#>  6 1.130666 42.41143   5358.809
#>  7 1.130424 42.41119   5382.372
#>  8 2.161639 41.38144 140476.0  
#>  9 2.160173 41.37800 140722.9  
#> 10 2.195302 41.41681 138891.3  
#> 11 2.195302 41.41681 138891.3  
#> 12 1.244259 42.51506  11500.29 
#> 13 2.195302 41.41681 138891.3  
#> 14 2.106953 41.51058 126116.0  
#> 15 2.198383 41.44021 136955.3  
#> 16 2.161639 41.38144 140476.0  
#> 17 2.160173 41.37800 140722.9  
#> 18 1.875368 42.23490  59584.02 
#> 19 1.880841 41.94424  77353.48 
#> 20 2.195302 41.41681 138891.3
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by krlmlr** [comment]
Thanks for the clarification. I opened #312 to track this issue. As the issue here is about a different problem, I'm hiding the most recent comments.

**Comment by krlmlr** [comment]
It looks like the following approach might work:

- We look at the data and compute the number of extra significant digits needed to show the relevant details
- We add that number to our `sigfig` value
- This could be a new argument to `num()`, and perhaps become the default at some point if it's useful

The following reprex proposes an implementation. We're sorting the data, looking at adjacent differences and determine the magnitude of the difference relative to the value. The decimal logarithm translates this to a number of extra significant digits.

Does that make sense? Can you think about cases where `extra_digits()` doesn't work as intended?

``` r
library(pillar)

extra_digits <- function(x) {
  x <- sort(abs(x))
  delta <- diff(x)
  x <- x[-1]

  keep <- which((delta != 0) & is.finite(delta))
  if (length(keep) == 0) {
    return(0)
  }

  x <- x[keep]
  delta <- delta[keep]

  ceiling(log10(max(x / delta)))
}

num_with_extra_digits <- function(x) {
  num(x, sigfig = 3 + extra_digits(x))
}

my_numbers <- c(233, 486, 565, 785)

tibble::tibble(
  big = num_with_extra_digits(1000 * my_numbers + 23),
  straddle = num_with_extra_digits(my_numbers / 1000 + 100),
  straddle2 = num_with_extra_digits(my_numbers / 1000 + 1000),
  straddle3 = num_with_extra_digits(my_numbers / 10000 + 10000),
  small = num_with_extra_digits(my_numbers / 100000)
)
#> # A tibble: 4 × 5
#>       big straddle straddle2  straddle3   small
#>   <num:4>  <num:7>   <num:8>   <num:10> <num:4>
#> 1  233023  100.233  1000.233 10000.0233 0.00233
#> 2  486023  100.486  1000.486 10000.0486 0.00486
#> 3  565023  100.565  1000.565 10000.0565 0.00565
#> 4  785023  100.785  1000.785 10000.0785 0.00785
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by charliejhadley** [comment]
Hey @krlmlr as I originally opened this issue I wanted to answer your question - other folks who've commented may have additional comments.

This solves my needs. I'll think about cases where it doesn't work as expected.

I see that `num()` is currently `lifecycle::signal_experimental()` but there is a vignette for it. I wonder how user's would find this functionality? Would it be expensive/too intrusive to generate a message for users the first time (per session) that the `100.` formatting is used by `{pillar}`?

**Comment by krlmlr** [comment]
Thanks. I checked the documentation, there is a path that leads from `?tibble` via `?tbl_df-class`, `?formatting`, and `?num` to `?pillar:num`. I agree it's a bit long, happy to revisit in the tibble repository. Would you like to open an issue there?

In the meantime I'll extend `num()` here.
